apiVersion: v1 
kind: ConfigMap 
metadata: 
 name: user 
 namespace: roboshop 
 labels: 
  component: user
  project: roboshop
  tier: app
data: 
  MONGO: "true" 
  REDIS_URL: "redis://redis:6379" 
  MONGO_URL: "mongodb://mongodb:27017/users"


